name: CI
on: [push, pull_request]
jobs:
  cs-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: 8.3
          coverage: none
      - name: install PHP CS Fixer
        uses: ramsey/composer-install@v2
        with:
          composer-options: '--working-dir=tools/php-cs-fixer'
      - name: 'php-cs-fixer check'
        run: 'tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --dry-run --diff'
  tests:
    runs-on: ubuntu-latest
    name: tests
    strategy:
      fail-fast: false
      matrix:
        php-versions:
          - 8.2
          - 8.3
        symfony-versions:
          - 6.4.*
          - 7.0.*
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: cache-composer
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/
          key: composer-${{ github.sha }}
      - name: setup
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '${{ matrix.php-versions }}'
          coverage: none
          extensions: mbstring, fileinfo, json, intl, dom
      - name: Install Symfony Flex
        run: |
          composer global config --no-plugins allow-plugins.symfony/flex true
          composer global require --no-progress --no-scripts --no-plugins symfony/flex
      - name: composer update
        run: composer update --prefer-dist
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-versions }}"
      - name: tests
        run: SYMFONY_DEPRECATIONS_HELPER="disabled=1" vendor/bin/simple-phpunit
